### ISSUE TITLE
Pycrypto is dead, requirement could switch to Pycryptodome?

### ISSUE THREAD

**Issue by adpeters** [ahknight/httpsig#10]
PyCrypto is dead, #https://github.com/dlitz/pycrypto/issues/238, and it won't work with Python 3.6 on Windows. 

Perhaps httpsig should require pycryptodome instead of pycrypto. I created a fork with these changes and it seems to work fine so far with all tests passing.

**Comment by iandouglas** [comment]
I submitted a PR for this, hopefully @ahknight or @atl can look into this soon.

**Comment by ahknight** [comment]
Merged. Thanks!
