### ISSUE TITLE
Path component of (request-target) header field value should be lower-cased?

### ISSUE THREAD

**Issue by cgascoig** [ahknight/httpsig#12]
The IETF draft spec (ver 09) says:
```
       If the header field name is `(request-target)` then generate the
       header field value by concatenating the lowercased :method, an
       ASCII space, and the :path pseudo-headers (as specified in
       HTTP/2, Section 8.1.2.3 [6]).
```
This could be read to mean either that just the `:method` pseudo-header should be lower-cased or that both `:method` and `:path` should be lower-cased. The service that I'm working with definitely seems to expect both to be lower-cased. 

Essentially, I think this line in `utils.py`:
```
            signable_list.append('%s: %s %s' % (h, method.lower(), path))
```
should be changed to:
```
            signable_list.append('%s: %s %s' % (h, method.lower(), path.lower()))
```

**Comment by ahknight** [comment]
I wrote this for draft 4 and haven't gotten around to updating it for the latter drafts (though as of draft 6 I hadn't noticed more than grammatical changes). I'll look again.

**Comment by ahknight** [comment]
Re-reading Draft 8 and all the spec changes up to it, only the header names are lowercased — the bodies of the headers are universally used unchanged. The HTTP method and path are treated as a special form of header (hence "pseudo-headers") and the method is called out as lowercase, but the path is not.

If your service requires a lowercase path, I'd suggest transforming it before making the call to the library as I believe that's a non-standard usage of the specification.
