### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('httpsig')

### ISSUE THREAD

**Issue by rubensayshi** [ahknight/httpsig#5]
Trying to use `httpsig` as `install_requires` in my `setup.py` but `python setup.py install` keeps failing with:

`Could not find suitable distribution for Requirement.parse('httpsig')`

Happens with both py2.7 and py3.4

Testing with:

``` python
from setuptools import setup

setup(
    name='test-httpsig',
    install_requires=[
        'httpsig'
    ]
)
```

`pip install httpsig` works fine though

**Comment by mmautner** [comment]
```pip install httpsig``` fails for me, looks like it's 404ing on PyPI:

```
Exception information:
Traceback (most recent call last):
  File "/Users/max/.virtualenvs/updownpic/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/Users/max/.virtualenvs/updownpic/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/max/.virtualenvs/updownpic/lib/python2.7/site-packages/pip/req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Users/max/.virtualenvs/updownpic/lib/python2.7/site-packages/pip/index.py", line 265, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for httpsig==1.1.0
```

**Comment by tbarbugli** [comment]
@mmautner what version of pip are you using? if `pip -V` is older than 6.0 you probably need to upgrade pip in order to get httpsig installed

**Comment by mmautner** [comment]
thanks @tbarbugli -- that was the issue!

**Comment by tbarbugli** [comment]
any plan of fixing the source of this problem? this problem really breaks libs/apps depending on httpsig.

if you release a python package and add httpsig in the requirements (setup.py) chances are that `python setup.py install` will fail

**Comment by ahknight** [comment]
I'm not sure what the source of it is at the moment.  I'll look into it, but if you know, do share.

**Comment by matthisk** [comment]
This issue occurs because there is only a ``wheel`` distributable available at [pypi](https://pypi.python.org/simple/httpsig/). ``pip`` handles the ``.whl`` package correctly but somehow ``setuptools`` refuses to install the wheel distributable. As a test I registered my own version of httpsig on [pypi](https://pypi.python.org/pypi/matthisk_httpsig) which is uploaded by running ``python setup.py sdist upload`` and this packages does not suffer from the same issue. Is there any reason you only distribute a wheel package, could you also publish it as a tarball?

**Comment by matthisk** [comment]
@ahknight any update on this?

**Comment by ahknight** [comment]
Uploaded this.  Let me know how it goes on your end.
