### ISSUE TITLE
Please upload an 'sdist' to PyPI as part of your release process

### ISSUE THREAD

**Issue by tseaver** [ahknight/httpsig#7]
An `sdist` is the "lowest-common denominator" for the Python packaging ecosystem.  It is more directly auditable against the sources than a `none-any` wheel, and is consumable in environnments where third-party binaries are not workable (e.g., see https://github.com/buildout/buildout/issues/144#issuecomment-207738962).

**Comment by ahknight** [comment]
I just sent one up. Let me know if that works for you.

**Comment by tseaver** [comment]
Thanks very much -- it does indeed.
