### ISSUE TITLE
CaseInsensitiveDict incompatible with normal dict ?

### ISSUE THREAD

**Issue by ldng** [ahknight/httpsig#8]
I might have found a bug. Unless I'm missunderstanding something.
If you try to merge an existing normal dict the result is None
Tested with Python 3.5.1 :

``` python
    import httpsig
    from email.utils import formatdate

    headers = {'whatever': 'the weather' }
    signed_headers_dict = hs.sign(
        {'Date': formatdate(timeval=None, localtime=False, usegmt=True), 'Host': '127.0.0.1:8000'},
        method='GET',
        path='/'
    )
    headers = headers.update(signed_headers_dict)
    print header # wil be None
    headers = signed_headers_dict.update(headers)
    print header # wil be None
```

**Comment by ldng** [comment]
I see my mistake, I should not be trying to modify headers after signing them anyway.
So this bug is irrelevant in httpsig usecase (still an CaseInsensitiveDict bug though IMHO)

**Comment by ldng** [comment]
Ok, I'm confused. I'll let someone else judge the relevancy of the bug.

**Comment by ahknight** [comment]
I should probably use the headers object from the email package here, honestly. It's designed for HTTP headers as well and does the same things I'm expecting. It's just more code to get to the same end.
